### ISSUE TITLE
With VoodooI2C 2.1.2 and 2.1.3 have problem in sleep and wake.

### ISSUE THREAD

**Issue by gujiangjiang** [alexandred/VoodooI2C#105]
XPS 15 9550

1.
VoodooI2C 2.1.2 and 2.1.3 will cause black screen when wake up from sleep and VoodooI2C 2.1.1 with no this problem.
2.
VoodooI2C 2.1.2 and 2.1.3 use native preferencepanel and i wish to be this but the function was have big problem.
Such as [Secondary click (right-click) Click or tap with two fingers] have no function.
And the [Open Notification Center] be more unreliable and will have no function when wipe more times.

So i must reback to VoodooI2C 2.1.1 3-rd fixed version for macOS10.14 to make my laptop works.

**Comment by asoco** [comment]
Aspire A517-51G-532B, 2.1.3
Confirm for sleep problems, right click with to fingers work perfectly, notification center gesture not wokring

**Comment by anonymous-writer** [comment]
Same problem on my Laptop. No Trackpad after sleep and then seconds later black screen with kernel panic.

**Comment by alexandred** [comment]
Sleep issues should be fixed in v2.1.4 . Right click with right corner and two fingers is broken for the moment due to scaling - same reason notification centre gesture is broken. A fix for this will come in a future release when we figure out the scaling issues. I will therefore close this issue since the title refers to sleep.

**Comment by gujiangjiang** [comment]
With latest VoodooI2C 2.1.4 it has fixed sleep issues.
But scaling issues was still as before.

**Comment by anonymous-writer** [comment]
Hi alexandred,
Now works great for me too. Thank you for your outstanding work.

**Comment by LeeBinder** [comment]
Alexandre, @hieplpvip has found a work-around for the scaling issue in his fork, see [https://github.com/hieplpvip/VoodooI2C/commit/0a8208f992a364fe931752299c9625fa9280f50a](https://github.com/hieplpvip/VoodooI2C). It's just that he uses a smaller zone for his Zenbook trackpad than the one in your 2.0.3 driver.

It would be awesome if you could use his work-around but with the values from your 2.0.3 version.

**Comment by hieplpvip** [comment]
@LeeBinder My fork of VoodooI2C is made for my laptop, nothing guarantee that it will work on all laptops. It's also the reason why Alexandre hasn't fixed the scaling issue, as he hasn't found a universal solution

**Comment by gujiangjiang** [comment]
@hieplpvip 
Tested your build with my XPS15 and the **[Open Notification Center]** works perfectly.

However,the **[Secondary click (right-click) Click or tap with two fingers]** still unreliable and sometime with no response.

**Comment by LeeBinder** [comment]
> @LeeBinder My fork of VoodooI2C is made for my laptop, nothing guarantee that it will work on all laptops. It's also the reason why Alexandre hasn't fixed the scaling issue, as he hasn't found a universal solution

@hieplpvip To keep discussions here limited to Alexandre's release I was going to reply in your github account issues section, but that's deactivated, so I'll reply to you directly.
