### ISSUE TITLE
Single click registers as a double click

### ISSUE THREAD

**Issue by Hi1307** [alexandred/VoodooI2C#111]
Seems to be happening on the Xiaomi Notebook Pro, where opening a desktop stack will immediately close it too, and single clicking on a file will open it.

This occurs in versions 2.1.2, 2.1.3 and 2.1.4

**Comment by alexandred** [comment]
I just tested this on my own machine and I appear to have the same issue - it only appears to happen with a very fast singe click. If I hold the click a bit then it seems to go through fine. I have a feeling what is happening is that the MT2's tap to click is registering at the same time as our click (we do not send clicks to the MT2 simulator - we send them to the system ourselves).

I'll have a think about how to approach it.

**Comment by Hi1307** [comment]
Yes I have noticed it too, holding for a while will make it register as a single click. Glad it's reproducible.

**Comment by anmoolpk** [comment]
hi alexandred Elan0608 trackpad  was perfectly working on version 2.0.3 but on version 2.1.4 right click and left click is not working  please fix this issue

**Comment by penghubingzhou** [comment]
> I just tested this on my own machine and I appear to have the same issue - it only appears to happen with a very fast singe click. If I hold the click a bit then it seems to go through fine. I have a feeling what is happening is that the MT2's tap to click is registering at the same time as our click (we do not send clicks to the MT2 simulator - we send them to the system ourselves).
> 
> I'll have a think about how to approach it.

I just watched  this issue  and  then tested  it，but  I don't have  this  problem， why？

**Comment by Hi1307** [comment]
> > I just tested this on my own machine and I appear to have the same issue - it only appears to happen with a very fast singe click. If I hold the click a bit then it seems to go through fine. I have a feeling what is happening is that the MT2's tap to click is registering at the same time as our click (we do not send clicks to the MT2 simulator - we send them to the system ourselves).
> > I'll have a think about how to approach it.
> 
> I just watched this issue and then tested it，but I don't have this problem， why？

Is your trackpad using ELAN or precision drivers in Windows?

**Comment by penghubingzhou** [comment]
> > > I just tested this on my own machine and I appear to have the same issue - it only appears to happen with a very fast singe click. If I hold the click a bit then it seems to go through fine. I have a feeling what is happening is that the MT2's tap to click is registering at the same time as our click (we do not send clicks to the MT2 simulator - we send them to the system ourselves).
> > > I'll have a think about how to approach it.
> > 
> > 
> > I just watched this issue and then tested it，but I don't have this problem， why？
> 
> Is your trackpad using ELAN or precision drivers in Windows?

nope  my touchpad  is synaptics

**Comment by coolstar** [comment]
Fixed in commit 6144caa54ec86cd9e8771d41ee56456f45150166

**Comment by Hi1307** [comment]
Works as expected
