### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by cowpod** [alexandred/VoodooI2C#114]
Hi! Amazing work! I'd like to report a few non-breaking issues.
The first is if you enable dragging, drag lock is enabled regardless if "drag lock" is selected or not (in accessibility). 
Even less important, is reduced sensitivity - I know it was possible to change a setting in Info.plist, but I can't find it, so I assume it was removed? 

Trackpad: ELAN1200, VoodooI2CHID

**Comment by alexandred** [comment]
With regards to drag lock, read the Supported Gestures page (in short this is Apple's fault, not ours).

I don't know what sensitivity settings you are referring to.

**Comment by michielglibert** [comment]
I think this person is referring to the trackpad sensivity (the speed of the movement of the cursor). My sensivity is also reduced since V2.1, even when set to maximum in the trackpad settings.
