### ISSUE TITLE
Is It Possible to Setup "Dell083F" i2c touchpad?

### ISSUE THREAD

**Issue by twikoffin** [alexandred/VoodooI2C#121]
Hello. I have a laptop
![1539777424](https://user-images.githubusercontent.com/32393163/47084688-f10edb00-d21c-11e8-8b68-dc60efb758a7.jpg)
(DSDT PATCHED)
Dell Inspiron 3576
CPU: Intel Core i5 8250u
GPU: AMD Radeon 520 (disabled via -wegnoegpu)
RAM: Micron 8GB DDR4 
OS: Mac OS Mojave
Touchpad: Dell083F on I2C
Keyboard: PS/2 (enabled via ApplePS2SmartTouchpad.kext, because VoodooPS2.kext sometimes (very very often) not responding on key presses.

So, can I setup this Touchpad?

**Comment by ben9923** [comment]
Yes, follow the installation guide:
https://voodooi2c.github.io/#Installation

If you need some help, post troubleshooting files in the Gitter chat.
