### ISSUE TITLE
please help me！

### ISSUE THREAD

**Issue by yaozaiyu** [alexandred/VoodooI2C#124]
My device is 9550, voodooi2chid, not loaded.

![Uploading 5CE6BEB8-A0A3-4FE3-AA83-787168E5BF9D.png…]()

**Comment by yaozaiyu** [comment]
![5ce6beb8-a0a3-4fe3-aa83-787168e5bf9d](https://user-images.githubusercontent.com/25170955/47428128-e88e4580-d7c4-11e8-93d5-e0aa55f6c06e.png)

**Comment by yaozaiyu** [comment]
![b0374a1c-0dc5-41c8-9ae1-3105fb39aa8d](https://user-images.githubusercontent.com/25170955/47428327-86821000-d7c5-11e8-9ff9-b50a1d96f7ab.png)

**Comment by alexandred** [comment]
This is not an appropriate place for this question. You should ask for help in the Gitter chat or on the various forums.
