### ISSUE TITLE
Build is impossible , what did I wrong ? 

### ISSUE THREAD

**Issue by giuligon** [alexandred/VoodooI2C#126]
![nuova nota](https://user-images.githubusercontent.com/43931014/47580475-48185c80-d94f-11e8-969c-c685c1906702.jpeg)
Hello everybody, as I read in a previous issue , to fix incorrect scaling we must deal with  "VoodooI2CMT2Simulator.cpp", so I'm going to fix the values , but when I build that I got into that error . Sorry  but I'm not skillful at using Xcode.
I'm on Mojave

**Comment by stevezhengshiqi** [comment]
A workaround for me is to open the `Build Phases`, delete `Generate Document` and `Linting`.

**Comment by giuligon** [comment]
Thanks a lot ! It works !

**Comment by BesnikRrustemi** [comment]
Can you explain please where i can find "Build Phases, so i can delete Generate Document and Linting
