### ISSUE TITLE
VoodooI2C ELAN KP when swiping

### ISSUE THREAD

**Issue by ghost** [alexandred/VoodooI2C#134]
The Voodoo ELAN or Voodoo I2C module causes a kernel panic when you swipe four fingers along the touch pad.

To replicate, drag four or five fingers along the laptop and across the touch pad a few times and the system will KP and reboot.  Can not recreate with 1-3 fingers.

Asus Q405UA
Mojave 10.14.1
Voodoo I2C 2.1.4

Happy to provide any additional debug data requested.

**Comment by alexandred** [comment]
Please provide a copy of the KP log with the "Keep debug symbols" option enabled in Clover.

**Comment by andrewwyatt** [comment]
No problem, attached.

[Kernel panic.zip](https://github.com/alexandred/VoodooI2C/files/2592135/Kernel.panic.zip)

**Comment by alexandred** [comment]
You are using VoodooI2CUPDDEngine.kext. The one bundled with v2.1.4 was inadvertently compiled against an old source of VoodooI2CUPDDEngine. You can try replacing it with the one from v2.1.3 and see if that works.

That being said, are you sure you need VoodooI2CUPDDEngine? It should only be installed if youre actually using it to connect to Touch Base's API.
