### ISSUE TITLE
Trackpad stops working with kexts beyond v2.0.2

### ISSUE THREAD

**Issue by onemanosx** [alexandred/VoodooI2C#141]
My trackpad only seems to work with Release v2.0.2. Updating to new kexts beyond that, trackpad will not function. I attach reporting files as requested.

[onemanosx-I2C report.zip](https://github.com/alexandred/VoodooI2C/files/2712380/onemanosx-I2C.report.zip)

Other debugging files
[onemanosx-Send me MacBook-Pro.zip](https://github.com/alexandred/VoodooI2C/files/2716527/onemanosx-Send.me.MacBook-Pro.zip)

Added sudo kextcache -i
[sudo kextcache -i.zip](https://github.com/alexandred/VoodooI2C/files/2716808/sudo.kextcache.-i.zip)

**Comment by alexandred** [comment]
Go to Sys Prefs > Accessiblity > Mouse & Trackpad and make sure "Ignore builtin trackpad" is not enabled.

**Comment by onemanosx** [comment]
Your suggestion works!! This is great news!
