### ISSUE TITLE
Two-finger right click only works with tap-to-click

### ISSUE THREAD

**Issue by b2550** [alexandred/VoodooI2C#142]
I am using VoodooI2CHID and I can only use right-click when I have tap-to-click enabled.

This is annoying because I constantly make accidental clicks with my trackpad when typing on my laptop. Since there is no good way to disable the trackpad while typing, I feel like adding right-click without tapping is the easier fix.

**Comment by ech1965** [comment]
I have the very same issue ( XPS 9550) and fully agree to the proposed solution ;-)

**Comment by alexandred** [comment]
This is addressed with the latest commits and will find its way into release soon.

Also it is not true that there is no way to disable the trackpad while typing. The latest VoodooI2C + the latest VoodooPS2 implements this fine.
