### ISSUE TITLE
Multitouch HID Event Driver Out of Date

### ISSUE THREAD

**Issue by vettz500** [alexandred/VoodooI2C#145]
I went ahead and built the latest kexts from the repo, but after installing the kexts I get the attached error upon booting. 
![img_20190110_174614](https://user-images.githubusercontent.com/43915319/51003283-194c6400-1504-11e9-8866-1af0a55122de.jpg)

If I remove the 2CHID kext, I can boot fine, just no trackpad. I've rebuilt the kexts a few times now with the same issue. The 2CHID kext is what I've used in the past with no issue, just wanted to run the newer version to fix the memory leak issue and fix the obnoxious Kernel Task CPU usage I was having because of it.

**Comment by alexandred** [comment]
What version of macOS are you running and building against?

**Comment by vettz500** [comment]
> What version of macOS are you running and building against?
> […](#)
> On 10 Jan 2019, at 23:18, vettz500 ***@***.***> wrote: I went ahead and built the latest kexts from the repo, but after installing the kexts I get the attached error upon booting. If I remove the 2CHID kext, I can boot fine, just no trackpad. I've rebuilt the kexts a few times now with the same issue. The 2CHID kext is what I've used in the past with no issue, just wanted to run the newer version to fix the memory leak issue and fix the obnoxious Kernel Task CPU usage I was having because of it. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Running 10.13.6 build# 17G3025

I just realized that in Xcode the Deployment Target was set to 10.11. Could the be the cause?

**Comment by alexandred** [comment]
Could be the target but also check the SDK that you’re building with.

**Comment by vettz500** [comment]
> Could be the target but also check the SDK that you’re building with.
> […](#)
> On 11 Jan 2019, at 01:07, vettz500 ***@***.***> wrote: What version of macOS are you running and building against? … On 10 Jan 2019, at 23:18, vettz500 ***@***.***> wrote: I went ahead and built the latest kexts from the repo, but after installing the kexts I get the attached error upon booting. If I remove the 2CHID kext, I can boot fine, just no trackpad. I've rebuilt the kexts a few times now with the same issue. The 2CHID kext is what I've used in the past with no issue, just wanted to run the newer version to fix the memory leak issue and fix the obnoxious Kernel Task CPU usage I was having because of it. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. Running 10.13.6 build# 17G3025 I just realized that in Xcode the Deployment Target was set to 10.11. Could the be the cause? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Just checked and for some reason it's set for sdk macosx10.14 
![screen shot 2019-01-10 at 8 16 15 pm](https://user-images.githubusercontent.com/43915319/51007203-9da6e300-1514-11e9-8dc7-f9bca39930bf.png)

**Comment by vettz500** [comment]
> And what about changing the SDK you build with in the actual build settings of VoodooI2C and its satellites?

Same issue. I even tested with the latest commits you applied to the Satellite kexts from yesterday.

**Comment by ben9923** [comment]
This is probably an SDK issue, as @alexandred suggested.
Are you sure you didn't build with the 10.14 SDK? What's the value of `DTSDKName`in the output `VoodooI2C.kext/Contents/Info.plist`?
It seems like the 10.14 SDK is not backwards compatible to 10.13.6 and below. Try the latest [10.12/10.13 SDK](https://github.com/alexey-lysiuk/macos-sdk/releases) (you can build VoodooI2C and all of the satellites with the same SDK using the `-sdk` parameter of xcodebuild). Refer to the [CircleCI build script](https://github.com/alexandred/VoodooI2C/blob/master/.circleci/config.yml).

The latest v2.1.6, for example, was built with the macosx10.12 SDK. It should work fine on your system.
