### ISSUE TITLE
Surface Pro 3 touch screen does not work ver.2.1.4 MacOS 10.13.6

### ISSUE THREAD

**Issue by rina-inverse** [alexandred/VoodooI2C#151]
Surface Pro 3 Core i 5 4300 U 1.9 GHz
VoodooI 2 C.kext VoodooI 2 CHID.kext ver 2.1.4
install to EFI / CLOVER / ketxs / Other
MacOS 10.13.6

Looking at IOReg, VoodooI2C.kext and VoodooI2CHID.kext seem to be loaded.
Trackpad settings are displayed in the environment settings.

The touch panel does not respond.

SysPrefs> Accessibility> Mouse & Trackpad> Ignore built-in ... is disabled.

attach Type Cover to surface pro 3.

The trackpad of type cover is working.
If I enable SysPrefs> Accessibility> Mouse & Trackpad> Ignore built-in ..., trackpad of type cover will not work.

With type cover trackpad, I can scroll with 2 fingers, etc.
Even if you remove the type cover from the surface pro 3, the touch panel will not respond.
Can I change the operation by trackpad of type cover to operation by touch panel?
 
It works with ver 1.0.4.
For ver 2.0.0 to ver 2.0.2, it will only work for about 10 seconds after starting on the login screen.
After about 10 seconds, the touch panel will stop responding.
Ver 2.0.3 and later will not work at all.

**Comment by rina-inverse** [comment]
files made by gen_debug.sh
[debug_3277.zip](https://github.com/alexandred/VoodooI2C/files/2798765/debug_3277.zip)

**Comment by 5high** [comment]
Hi，rina-inverse

did you patched your DSDT?

**Comment by ittat** [comment]
> Hi，rina-inverse
> 
> did you patched your DSDT?
How to patch it ?

**Comment by ben9923** [comment]
That issue was inactive for over a year...
Please re-open with updated troubleshooting files if it still happens with latest release.
