### ISSUE TITLE
gesture doesnt match with settings, elan 0501

### ISSUE THREAD

**Issue by hilmanshini** [alexandred/VoodooI2C#152]
i have elan 0501, but it seems i cant get it to work with mojave , i cant seems to rotate image with these kexts, but i can swipe three fingers left/right to switch desktop, is it possible to make it work?

**Comment by alexandred** [comment]
This is not a suitable format for a Github issue. I will close this until you provide proper troubleshooting archives as requested on the troubleshooting page.
