### ISSUE TITLE
Probable Kernel Panic  after  changed  EFI

### ISSUE THREAD

**Issue by penghubingzhou** [alexandred/VoodooI2C#153]
it's a probabilistic  KP .  It  will  happen  after changed  EFI (such  as  update kext , or reboot). And it is irregular. This  is  the  KP log.
[KP.txt](https://github.com/alexandred/VoodooI2C/files/2802670/KP.txt). 

Using Atos I found  this code：``` UInt32 address = messages[bus_device->message_write_index].address;``` got  this  KP but  I can't  figure out  what  caused  it .

**Comment by penghubingzhou** [comment]
By  comparing  IOKIT and `` VoodooI2CControllerDriver.hpp```  I figured out  a  simple  way to solve it :  changing ```UInt16 address;``` to ```UInt32 address;``` .

**Comment by penghubingzhou** [comment]
I believe ```messages[bus_device->message_write_index].address;``` should be a uint32 rather  than uint16

**Comment by persistz** [comment]
+1 panic too

**Comment by penghubingzhou** [comment]
@alexandred
 Sorry for so lang  reply, now I have tested in  OC and it will be  a  real "kernel panic". I  have no ideas for now.

**Comment by penghubingzhou** [comment]
I think it's time to close this issue temporary because after I replace XOSI with this code, my panic disappeared:
```
Scope (\)
    {
        If (_OSI ("Darwin"))
        {
            Store (One, TPDD)
        }
    }
```
I still need more information about it to prove it's VoodooI2C's issue not a DSDT issue. So if anyone have sth useful pls contact me, thx!
