### ISSUE TITLE
ELAN 0608

### ISSUE THREAD

**Issue by rogerzero** [alexandred/VoodooI2C#156]
Gesture doesn't work on ELAN0608.
System Preference doesn't detect the touchpad.
Any solution?

**Comment by penghubingzhou** [comment]
ELAN0608 can  be  dectected  in  syspref  with  i2celan.   But now  it has  bug.

**Comment by rogerzero** [comment]
mine doesn't, should i do something?
what bug you referenced?

**Comment by penghubingzhou** [comment]
You  need  to follow  the  gpio  pinning  guide  to  makesure  it run in  interrupt  mode  and  then  use i2celan  as satellite kext. The  bug  is it only  display in syspref but has  no  gesture  in  reality.





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by penghubingzhou** [comment]
Now  it's  prooved  that elan0608 can  work  with i2celan satellite. Lenovo Chao 5000 succeed.

**Comment by rogerzero** [comment]
what do you mean by satellite?

**Comment by penghubingzhou** [comment]
> what do you mean by satellite?. I did the gpio pinning, but yet, not detected in syspref but the touchpad is working (no gesture).

You should  use VoodooI2CELAN as satellite kext. See  voodooi2c.github.io  for  more  details.
