### ISSUE TITLE
The FTE touchpad settings have been recognized, but the trackpad still does not work properly.

### ISSUE THREAD

**Issue by Xiaoshiguang520** [alexandred/VoodooI2C#157]
I tried to use the FTE2.14 driver, but it didn't work on my computer. I also tried putting the driver into the L\E build cache, and the trackpad still didn't work. Is there any way to solve the normal working problem of the FTE touchpad?

**Comment by Xiaoshiguang520** [comment]
System version: macos mojave10.14.3

**Comment by alexandred** [comment]
This is not a suitable format for a Github issue. I will close this until you provide proper troubleshooting archives as requested on the troubleshooting page.
