### ISSUE TITLE
Touchscreen gesture direction not changed when rotated

### ISSUE THREAD

**Issue by gongzhenjeef** [alexandred/VoodooI2C#161]
After rotated automatically with VoodooI2CSensorHub, single point input on the touchscreen matches but the gesture direction is still in vertical. Eg, three finger (haven't fixed yet) can do scroll up and down by swipe left and right.

**Comment by jieeraoyun** [comment]
@gongzhenjeef 

How do you achieve automatic screen rotation?

**Comment by gongzhenjeef** [comment]
There's just a SHUB device under the I2C0 controller. VoodooI2C could recognize it and get some of the data. While I suppose there might be more data like brightness signal from the sensor hub.

**Comment by alexandred** [comment]
> @gongzhenjeef
> 
> How do you achieve automatic screen rotation?This function is cool。
> 
> #115 issue has been soloved by blankmac。

Sensor Hub support is in beta and only works for a select few SHUBs.

**Comment by alexandred** [comment]
Closed as this is a clone of https://github.com/alexandred/VoodooI2C/issues/148.
