### ISSUE TITLE
ELAN 1300 not working

### ISSUE THREAD

**Issue by angpysha** [alexandred/VoodooI2C#162]
Hi I have Asus Vivobook Pro 15 X580VD. 
Processor: Intel Core i7-7700HQ
OS X: 10.14.3
Latest VoodoI2C and HCID.
And I have a problem touch is detected, but not works.
[info.zip](https://github.com/alexandred/VoodooI2C/files/2928001/info.zip)
![image](https://user-images.githubusercontent.com/7025170/53759560-49dbc900-3ec9-11e9-9131-a7fdfb63f61e.png)
Can you help me?

**Comment by penghubingzhou** [comment]
You  should try to rebuild kextcache first. If  it don't  work, send trb shooting  file here

**Comment by alexandred** [comment]
No evidence of GPIO pinning applied. You should read the installation instructions and seek further help in the GItter chat room.
