### ISSUE TITLE
The touchpad stops working when closing the type cover of Surface Pro 4

### ISSUE THREAD

**Issue by alphonse2019** [alexandred/VoodooI2C#163]
It is used in the following environment.

Surface Pro 4 + Surface Pro 4 type cover
Mac OS 10.14.3
The latest firmware is applied to Surface Pro 4.
VoodooI 2 C + VoodooI 2 CHID We got the latest source code from github, built on Voodoo I 2 CHID with keyboard support pull request modified, installed on Clover / kexts / other.

Although the touchpad is working normally, the touchpad stops operating when the type cover is closed and reopened.
If you select Sleep from the menu and put it to sleep, or if you automatically go to sleep without doing any operation for a certain period of time, the touchpad is working.

I attach a file for debugging.
[debug_7619.zip](https://github.com/alexandred/VoodooI2C/files/2935477/debug_7619.zip)

**Comment by blankmac** [comment]
This isn’t an issue with VoodooI2C, but rather with the ACPI methods in your DSDT/SSDTs associated with type cover or ‘lid’ initiated sleep.
