### ISSUE TITLE
Touch pad does not work with combination of Surface Pro 4 + Surface Pro 3 type cover

### ISSUE THREAD

**Issue by alphonse2019** [alexandred/VoodooI2C#164]
The touch pad does not work with the combination of Surface Pro 4 + Surface Pro 3 type cover.
It works with combination with Surface Pro 4 type cover.

**Comment by blankmac** [comment]
Post an ioreg with the surface pro 3 type cover attached please.

**Comment by alexandred** [comment]
This is not a suitable format for a Github issue. I will close this until you provide proper troubleshooting archives as requested on the troubleshooting page.
