### ISSUE TITLE
I2C controllers AMDI0010 can be suported? 

### ISSUE THREAD

**Issue by Trainspoting** [alexandred/VoodooI2C#165]
Hi have latop is amd ryzen 7 1700 all ok only the trackpad dont work says i2c say name device AMDI0010 can be installler?

**Comment by alexandred** [comment]
This is not a suitable format for a Github issue. I will close this until you provide proper troubleshooting archives as requested on the troubleshooting page.

**Comment by Trainspoting** [comment]
Can you give me the link troublesshooting page i cant find

**Comment by Trainspoting** [comment]
Trackpad is ELAN1200﻿ / SA473I﻿-﻿12A4
Controller is AMDI0010 this is what says ioreg
