### ISSUE TITLE
Adding elan_i2c_smbus support

### ISSUE THREAD

**Issue by leo-labs** [alexandred/VoodooI2C#166]
I would like to add support for elan touchpads that are attached via smbus. Such devices are e.g used in the Thinkpad T480s (here with trackpoint).
I have already seen some discussion on Gitter of the topic and did some research regarding how the touchpad works in linux, but I might need some help regarding DSDT patching and understanding interrupts.

Apparently the driver in the linux kernel uses the same elan protocol for `i2c` and `smbus` so the `VoodooI2CElan` satellite should work (it is heavily based on the linux kernels source code). Therefore is not yet clear to me, if it makes sense to extend VoodooI2C with elan specific smbus capabilities or write a complete new driver e.g. `VoodooElanSmbus`, but implementing the same interface. However I think the answer to that question will become more clear as development proceeds.

 As I see it, the very first step now is to expose the elan device on the smbus to mac, so I can write a driver that can register for it. Since there is no DSDT entry for the touchpad device, I guess I have to add it manually to the bus. The way this is currently done in the linux driver is via the `elantech` driver for an exposed PS2 device of the touchpad/trackpoint. That driver can query if the tochpad/trackpoint uses `host_notify` via smbus and then setups a new corresponding i2c device (https://github.com/torvalds/linux/blob/master/drivers/input/mouse/elantech.c#L1791-L1809) that will use the `elan_i2c` driver with smbus transport operations (https://github.com/torvalds/linux/blob/master/drivers/input/mouse/elan_i2c_smbus.c#L512)
The address of the device is hardcoded (at 0x15) and matches the output of `i2cdetect 0`.
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- 08 -- -- -- -- -- -- -- 
10: -- -- -- -- -- UU -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- 44 -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                          
```
From the man page: ` · "UU".  Probing  was skipped, because this address is currently in use by a driver. This strongly suggests that there is a chip at this address`

Currently I apply the following DSDT patch: https://github.com/linusyang92/macOS-ThinkPad-T480s/blob/master/EFI/CLOVER/ACPI/dsl/SSDT-SMBUS.dsl, the original DSDT looks like
```
 4777       Device (SBUS)
 4778         {
 4779             Name (_ADR, 0x001F0004)  // _ADR: Address
 4780             Method (_DSM, 4, Serialized)  // _DSM: Device-Specific Method
 4781             {
 4782                 If (PCIC (Arg0))
 4783                 {
 4784                     Return (PCID (Arg0, Arg1, Arg2, Arg3))
 4785                 }
 4786
 4787                 Return (Buffer (0x01)
 4788                 {
 4789                      0x00
 4790                 })
 4791             }
 4792         }
```

The output of `ioreg` shows
```
    | |   +-o SBUS@1F,4  <class IOPCIDevice, id 0x100000241, registered, matched, active, busy 0 (6314 ms), retain 11>
    | |   | +-o AppleSMBusPCI  <class AppleSMBusPCI, id 0x1000003e3, registered, matched, active, busy 0 (3127 ms), retain 6>
    | |   |   +-o BUS0@0  <class IOACPIPlatformDevice, id 0x1000001a0, registered, matched, active, busy 0 (3127 ms), retain 11>
    | |   |     +-o AppleSMBusControllerICH  <class AppleSMBusControllerICH, id 0x100000414, registered, matched, active, busy 0 (0 ms), retain 8>
    | |   |       +-o DVL0  <class AppleSMBusDevice, id 0x100000415, registered, matched, active, busy 0 (0 ms), retain 5>
```

I could add an elan device similar to the `DVL0` device. However I do not know if I need to expose other methods. Further I do not fully understand the `DVL0` device, it does not physically exists but seems to be a common patch. Would I need to replace the `AppleSMBusPCI` driver and the `AppleSMBusControllerICH` (which would probably not work with `DVL0`, or could I just attach below the `AppleSMBusPCI` driver. 

I know that you do not support smbus (yet) and I would understand if you cannot spend time on this issue, but it would be much appreciated. If this succeeds, the driver would support another device class.

**Comment by alexandred** [comment]
I will (tentatively) close this as there now exists a driver for SMBUS devices which is separate from VoodooI2C, available here: https://github.com/gokula/ELANSMBus.
