### ISSUE TITLE
Release 2.1.5 ?

### ISSUE THREAD

**Issue by hrytskivr** [alexandred/VoodooI2C#170]
First thanks for the job you've done, with that I can use my laptop's touchpad in macOS.

The question is, there's been a lot of commits to master since last release, any plans on new release?

**Comment by williambj1** [comment]
There are Releases [here](https://github.com/williambj1/VoodooI2C-PreRelease/releases)
And Some provided by @hieplpvip [here](https://github.com/hieplpvip/VoodooI2C/releases)

**Comment by hrytskivr** [comment]
Very good, thank you!!!
Those pre-releases will do for now, I guess, thanks!
