### ISSUE TITLE
ELAN1300 stop working after 5 minutes idle

### ISSUE THREAD

**Issue by wanttolove** [alexandred/VoodooI2C#173]
It's working perfectly but I must touch it continuously if not it will stop working. I have to restart my pc again
Thanks

**Comment by xiaominglei001** [comment]
Same question.Have you solve the problem?

**Comment by xiaominglei001** [comment]
> Same question.Have you solve the problem?

Have solved the problem, just fllow the indication(https://voodooi2c.github.io/) and edit DSDT file.

**Comment by ben9923** [comment]
Closing as issue wasn't updated for a while.
Please re-open & attach troubleshooting files if it's still happening with latest release :)
