### ISSUE TITLE
Conflicts with ACPIBatteryManager kext

### ISSUE THREAD

**Issue by hrytskivr** [alexandred/VoodooI2C#179]
I2C/HID kext conflicts with ACPIBatteryManager kext which makes touchpad "crazy-jumpy" when on battery power, everything goes back to normal when plugged-in though.
I'm using VirtualSMC/SMCBattery kexts instead of FakeSMC/ACPIBatteryManager to avoid this issue.
Any thoughts what might be the cause?

**Comment by LeeBinder** [comment]
@hrytskivr What's bad for you using VirtualSMC/SMCBattery kexts? Why would you prefer using FakeSMC/ACPIBatteryManager kexts?

**Comment by hrytskivr** [comment]
I have non-stable boot with those for some reason.
3 times out of 10 won't boot.

**Comment by LeeBinder** [comment]
Oh that sucks. I take for granted you have:
- FakeSMC removed
- VirtualSmc.efi present in drivers64UEFI
- SMCHelper-64.efi removed from drivers64UEFI
- both, VirtualSMC.kext and SMCBatteryManager.kext, installed correctly to /L/E (not just in Clover/kexts)
- updated all your kexts to latest versions, easiest via [Kext Updater](https://bitbucket.org/profdrluigi/kextupdater/downloads/)
- are running the latest version of Clover
?

**Comment by hrytskivr** [comment]
@LeeBinder
Everything but VirtualSmc.efi present in drivers64UEFI, I though it's necessary for FireVault stuff only

**Comment by LeeBinder** [comment]
@hrytskivr : oh you are right: "VirtualSmc-64.efi: Advanced Apple SMC Emulator. VirtualSMC.efi module is recommended for boot.efi compatibility when FileVault 2 is enabled"

https://github.com/acidanthera/VirtualSMC/blob/master/Docs/FAQ.md

**Comment by Richylitschy** [comment]
apparently the Voodoo kext and the ACPI kext use the same BUS, which thus gets overloaded. Read it somewhere on tonymac, so not 100% sure.

**Comment by FreeJHack** [comment]
I found the solution. Maybe could help, take a look.
https://www.tonymacx86.com/threads/solution-trackpad-voodooi2chid-conflicts-with-acpibatterymanager-kext.281416/

**Comment by hrytskivr** [comment]
Thanks @FreeJHack !
