### ISSUE TITLE
Cant get touchpad working on elan1300

### ISSUE THREAD

**Issue by yamvmax** [alexandred/VoodooI2C#194]
Have an ASUS VivoBook Flip 14 TP412UA-IH31T Has an elan1300. I tried the kexts, and editing my dstl, but the windows 10 edit, wont load or edit on my dsdt. Any ideas?

**Comment by ben9923** [comment]
GitHub issues are not the place for troubleshooting. Ask for help [in the Gitter chat](https://gitter.im/alexandred/VoodooI2C).
Make sure you attach the necessary troubleshooting files.
