### ISSUE TITLE
I2C ( ELAN3912 )

### ISSUE THREAD

**Issue by karle228** [alexandred/VoodooI2C#196]
I2C ( ELAN3912 ) it's compatible?

**Comment by ben9923** [comment]
It should work. GitHub issues isn't the place for questions like this.
Please ask for help in the Gitter chat (link in the README), and provide the necessary troubleshooting files.

**Comment by karle228** [comment]
Sorry, thanks

**Comment by karle228** [comment]
In BIOS os elan3912, in Windows and ioreg os MSSL1680, i have parched dsdt, any occurrence? Thx
