### ISSUE TITLE
ELAN 1400

### ISSUE THREAD

**Issue by andyWiles** [alexandred/VoodooI2C#197]
Hi !
ASUS Vivobook S430 is delivered with an ELAN 1400 trackpad.
Is there any chance to use VoodooI2C to make it work ?
Regards

**Comment by ben9923** [comment]
It should be supported, read the [installation guide](https://voodooi2c.github.io/#Installation).
If you need some help, ask for it in the [Gitter chat](https://gitter.im/alexandred/VoodooI2C) :)
