### ISSUE TITLE
kextd stall(60s):'applePS2MouseDevice'

### ISSUE THREAD

**Issue by sowhyim** [alexandred/VoodooI2C#200]
start with three kextd stall(60s):'applePS2MouseDevice' 

touchpad can work ,but no device in trackpad of system preferences

**Comment by ben9923** [comment]
Any PS2-related log/error is not related to VoodooI2C.
Remove your PS2 kext(s), or at least disable their trackpad/mouse component, to see if the error is gone.

If your touchpad is I2C/USB and you need help with installation, attach a troubleshooting archive in the [Gitter chat room](https://gitter.im/alexandred/VoodooI2C).
