### ISSUE TITLE
Touchpad Buttons ELAN 1200 

### ISSUE THREAD

**Issue by Emanuele-1998** [alexandred/VoodooI2C#207]
Hi @alexandred I managed to make the touchpad work but the mon keys work or work randomly only with some applications like itunes, when can you upgrade it?

**Comment by LeeBinder** [comment]
what are "mon keys" - what do you mean?

**Comment by Emanuele-1998** [comment]
> what are "mon keys" - what do you mean?

Sorry. I wrong, I meant the touchpad buttons
