### ISSUE TITLE
Trackpad lagging in GPIO mode since v2.1.4

### ISSUE THREAD

**Issue by Neon-Omega** [alexandred/VoodooI2C#209]
My trackpad is I2CHID  ELAN1200. It's working perfectly in version v2.1.3 . But from v2.1.4 to v2.2 all version lagging in GPIO mode. (No lag in Polling mode). So, i had to stick with v2.1.3.  maybe there's something from v2.1.4 which causing the lag. 
I have tried with different versions. The problem in somewhere inside VoodooI2C.kext.  not in VoodooI2CHID.kext . 
Thanks

**Comment by ben9923** [comment]
Duplicate of #192
