### ISSUE TITLE
Touchpad sometimes can't detect my finger

### ISSUE THREAD

**Issue by esefberfu** [alexandred/VoodooI2C#211]
when i want to control for only to move to cursor, sometimes touchpad does not detect my finger. so that i release the my finger and i again touch to touchpad for to control to cursor with only one finger. An other option, Touchpad that if i hold on one finger on work fine. So, one finger doesn't move and other finger control to cursor,
if i control with three fingers too  sometimes only two fingers is detected by touchpad and scrolling works

on Windows OS, touchpad don't has any problem, everything stable.
there is not any problem to scrolling with two fingers

**Comment by joeyave** [comment]
> if i control with three fingers too sometimes only two fingers is detected by touchpad and scrolling works

the same here.

**Comment by ben9923** [comment]
@esefberfu @joeyave Have you tried v2.4?

**Comment by joeyave** [comment]
> @esefberfu @joeyave Have you tried v2.4?
gonna try it now!

**Comment by joeyave** [comment]
> @esefberfu @joeyave Have you tried v2.4?

It works perfectly with 2.4. Thank you!
