### ISSUE TITLE
Touchpad acting strangely | Lenovo Ideapad 520-15IKB

### ISSUE THREAD

**Issue by djale** [alexandred/VoodooI2C#212]
Hello, I have Lenovo Ideapad 520-15IKB with macOS 10.14.4 
Specs are :
i5 8250u
mx150
8gb ram
ssd 240gb intel 

The touchpad is giving me headaches, when satellite CHID is used it "works" but very buggy, and it's not shown in system prefs (I have battery info working fine). 
Video : https://www.youtube.com/watch?v=aFscOezzPdU

If I change satelite to ELAN or Synaptics it doesn't work at all.

Thanks
[debug_12960.zip](https://github.com/alexandred/VoodooI2C/files/3566566/debug_12960.zip)

**Comment by ben9923** [comment]
Your device is Synaptics, vendor ID: `0x6cb`.
You didn't [patch for GPIO interrupts](https://voodooi2c.github.io/#GPIO%20Pinning), it's a requirement for VoodooI2CSynaptics (Your I2C ACPI setup seems messy, start over with that...). Once you complete it, change the name match in the kext's Info.plist to `SYNA2B3C`.

As GitHub issues isn't the place for installation support, I'll close this issue.
