### ISSUE TITLE
Problem with SYNA2B33

### ISSUE THREAD

**Issue by Dicky-MF** [alexandred/VoodooI2C#217]
I have some problem on I2C device it's SYNA2B33
When i drop VoodooI2CHID.kext (Of course i place VoodooI2C.kext too "On EFI/C/k/O")
The device (trackpad) is not working, and when i use VoodooI2CHID.kext it's work but not fine
It's still move the cursor until i give a (click) on trackpad, or sometime the touchpad is too sensitive (VERY SENSITIVE)
I have sompletely follow guide from Olarila
Patch DSDT, Pinning my ID, etc

Please someone give me a help

[Send me Fizers-MacBook-Pro.zip](https://github.com/alexandred/VoodooI2C/files/3657249/Send.me.Fizers-MacBook-Pro.zip)

**Comment by onemanosx** [comment]
You should be using VoodooI2CSynaptics instead of VoodooI2CHID for SYNA2B33

**Comment by Dicky-MF** [comment]
Alright, and then i just have to make TPD0._CRS hotpatch and _CRS work fine, right ?
* I inject GPI0 on DSDT

**Comment by onemanosx** [comment]
You already have native GPI0 pin. If you had really read the guide, all you have to do is make sure _CRS  Return (ConcatenateResTemplate (SBFF, SBFG). There is no need for you to use SSDT or hotpatches. The SSDT has the wrong configuration as I had pointed out in my earlier post.

Anyway, this is installation issue and all queries regarding installation should be directed to the gitter chat. https://gitter.im/alexandred/VoodooI2C

Please respect the Dev's rules.

**Comment by Dicky-MF** [comment]
Thanks for your help, i will read the guide carefully again

Issue closed, thanks
