### ISSUE TITLE
MSSL1680

### ISSUE THREAD

**Issue by karle228** [alexandred/VoodooI2C#227]
In BIOS os elan3912, in Windows and ioreg os MSSL1680, i have parched dsdt, any occurrence? Thx

**Comment by ben9923** [comment]
You'll need to attach a troubleshooting archive to the Gitter chat support.
It doesn't seem like an issue with the kext (which should be posted in the issues GitHub page)...

**Comment by fpx-one** [comment]
> You'll need to attach a troubleshooting archive to the Gitter chat support.
> It doesn't seem like an issue with the kext (which should be posted in the issues GitHub page)...

waiting you
