### ISSUE TITLE
Migrate VoodooI2C to VoodooInput

### ISSUE THREAD

**Issue by vit9696** [alexandred/VoodooI2C#228]
Hello,

Some while ago we got an issue regarding our VoodooPS2 additions to MT2 emulation layer (e.g. https://github.com/acidanthera/bugtracker/issues/329). With some combined effort Kishor (@kprinssu) and Michael (@usr-sse2) factored out the MT2 part to a separate kext: [VoodooInput](https://github.com/kprinssu/VoodooInput).

At this step we are migrating to it, starting with VoodooPS2 2.1.0, which is scheduled for release in the first days of December (https://github.com/acidanthera/bugtracker/issues/541). Therefore we request VoodooI2C to do the same in the nearest future.

Cheers,
Vit

**Comment by kprinssu** [comment]
Completed by https://github.com/alexandred/VoodooI2C/commit/7b83ae26d0e0e3e84bb0b2a817c512ccf6a07009.
