### ISSUE TITLE
This version of VoodooI2C can work with ELAN1200

### ISSUE THREAD

**Issue by lunjielee** [alexandred/VoodooI2C#230]
However I can't use my trackpad after upgrading to VoodooI2C 2.3
pci8086,a368 8750H

[Archive.zip](https://github.com/alexandred/VoodooI2C/files/3965184/Archive.zip)
![Screen Shot 2019-12-15 at 12 14 36 PM](https://user-images.githubusercontent.com/32808108/70866186-89dddb00-1f34-11ea-92cd-ab732c99215b.png)
![Screen Shot 2019-12-15 at 12 14 46 PM](https://user-images.githubusercontent.com/32808108/70866187-8b0f0800-1f34-11ea-86d0-08a2335fa709.png)

**Comment by ben9923** [comment]
You'll need to attach a full troubleshooting archive.

**Comment by lunjielee** [comment]
I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)

**Comment by ben9923** [comment]
> I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
> ![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)

This configuration is 100% invalid. INT3450 must only match CNL-H. Pin mapping is different for each platform.
Impossible to debug without appropriate troubleshooting files, and unmodified (correct) kexts...

**Comment by lunjielee** [comment]
> > I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
> > ![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)
> 
> This configuration is 100% invalid. INT3450 must only match CNL-H. Pin mapping is different for each platform.
> Impossible to debug without appropriate troubleshooting files, and unmodified (correct) kexts...

Sorry about the wait, here is my Troubleshooting files, hope this would help with solve the problem
[Archive.zip](https://github.com/alexandred/VoodooI2C/files/3986611/Archive.zip)

**Comment by lunjielee** [comment]
> > I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
> > ![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)
> 
> This configuration is 100% invalid. INT3450 must only match CNL-H. Pin mapping is different for each platform.
> Impossible to debug without appropriate troubleshooting files, and unmodified (correct) kexts...

btw I checked the log and found that polling mode works perfect but not GPIO
![Screen Shot 2019-12-19 at 10 46 03 PM](https://user-images.githubusercontent.com/32808108/71228806-57740b00-22b1-11ea-8386-6028777d7cd2.png)

**Comment by ben9923** [comment]
> > > I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
> > > ![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)
> > 
> > 
> > This configuration is 100% invalid. INT3450 must only match CNL-H. Pin mapping is different for each platform.
> > Impossible to debug without appropriate troubleshooting files, and unmodified (correct) kexts...
> 
> Sorry about the wait, here is my Troubleshooting files, hope this would help with solve the problem
> [Archive.zip](https://github.com/alexandred/VoodooI2C/files/3986611/Archive.zip)

Another unsupported configuration here - you have multiple, unnecessary satellite kexts (For example, VoodooI2CFTE).
Remove everything besides VoodooI2C and VoodooI2CHID.
Currently VoodooI2CELAN is attached to your device, while you should be using HID.

**Comment by lunjielee** [comment]
> > > > I tried to load INT3450 under VoodooGPIOSunrisePointH and VoodooGPIOSunrisePointLP by modifying Info.plist inside VoodooGPIO.kext and now problem solved
> > > > ![Screen Shot 2019-12-18 at 11 33 38 PM](https://user-images.githubusercontent.com/32808108/71145226-db18f380-21ee-11ea-87e2-780d0a2efe2a.png)
> > > 
> > > 
> > > This configuration is 100% invalid. INT3450 must only match CNL-H. Pin mapping is different for each platform.
> > > Impossible to debug without appropriate troubleshooting files, and unmodified (correct) kexts...
> > 
> > 
> > Sorry about the wait, here is my Troubleshooting files, hope this would help with solve the problem
> > [Archive.zip](https://github.com/alexandred/VoodooI2C/files/3986611/Archive.zip)
> 
> Another unsupported configuration here - you have multiple, unnecessary satellite kexts (For example, VoodooI2CFTE).
> Remove everything besides VoodooI2C and VoodooI2CHID.
> Currently VoodooI2CELAN is attached to your device, while you should be using HID (You have ELAN1200).
> 
> If you still experience issues after fixing this, attach a more comprehensive archive using this:
> https://github.com/black-dragon74/OSX-Debug
> Make sure IOReg is included.

New debug log:
[debug_18158.zip](https://github.com/alexandred/VoodooI2C/files/3989190/debug_18158.zip)

**Comment by ben9923** [comment]
> New debug log:
> [debug_18158.zip](https://github.com/alexandred/VoodooI2C/files/3989190/debug_18158.zip)
Your ACPI patching is wrong. I believe there is no bug, and GitHub issues is not the correct place for such troubleshooting.
You cannot have 2 DSDTs, values in _CRS are wrong and it's better to just patch `TPDM` to be equal to Zero than patching _CRS (To eliminate the need to patch `_INI` as well, and it's also quite simpler).
To continue troubleshooting please join the Gitter chat, there's a link in the README.
Keeping the issue open for now.
