### ISSUE TITLE
[SOLVED] VoodooI2C not working in Catalina

### ISSUE THREAD

**Issue by Hunter9888x** [alexandred/VoodooI2C#233]
Open Terminal copy paste below commands:

sudo mount -uw / && cd /System/Library/Extensions && sudo rm -rf AppleIntelLpssI2C.kext && sudo rm -rf AppleIntelLpssI2CController.kext && sudo kextcache -i /

INSTEAD OF RUNNING ABOVE COMMANDS 
could open hackintool click bootloader select bootloader patch kextstopatch prevent apple i2c from attaching to i2c controllers
Click check icon bottom of screen click ok & mount than overwrite replace config.plist

install all voodooi2c kext files with a kext installer i use hackintool
http://headsoft.com.au/download/mac/Hackintool.zip
Run hackintool click tools
Click install kexts bottom of screen
Install all voodooi2c kext files

Now install ACPIBatteryManager.kext
https://bitbucket.org/RehabMan/os-x-acpi-battery-driver/downloads/
Reboot hackintosh

**Comment by LeeBinder** [comment]
Recommended title:
**[FIX] VoodooI2C not working in Catalina**

**Comment by ben9923** [comment]
Those patches are not necessary with VoodooI2C v2.3+. It will load before Apple's I2C kexts.

**Comment by Hunter9888x** [comment]
Acpibatterymanager.kext is necessary to fix trackpad system preferences what are u talking about & yes u must disable apple i2c controller

**Comment by ben9923** [comment]
> Acpibatterymanager.kext is necessary to fix trackpad system preferences what are u talking about & yes u must disable apple i2c controller

I know a battery kext is necessary, it's a known issue for all hacks (not just I2C) for years. SMCBatteryManager is another, good alternative.

With version 2.3 you don't have to disable Apple's kexts, VoodooI2C can load before them.

GitHub issues is the place to document & discuss issues with the kext, I could not find any bug with the kext in this issue.

**Comment by Hunter9888x** [comment]
I never got voodooii2c kext to work without disabling applei2c controller

**Comment by ben9923** [comment]
> I never got voodooii2c kext to work without disabling applei2c controller

Have you tried latest release?
If you can reproduce this with latest release, attach a troubleshooting archive.

**Comment by Hunter9888x** [comment]
Voodooi2c 2.3 is version im on

**Comment by Hunter9888x** [comment]
For me anyway apple i2c controller gets loaded before voodooi2c

**Comment by ben9923** [comment]
Please attach a troubleshooting archive then, we cannot investigate without actual debug info.

**Comment by fewtarius** [comment]
@Hunter9888x, you absolutely do not need to disable Apple's kexts via patches or deletes nor do you need Acpibatterymanager.kext for version 2.3.  You do need working battery status but you can accomplish that with VirtualSMC + SMCBattery.  You may also need ForceKextsToLoad IOGraphicsFamily.kext. If you are still having trouble then you should enable the IRQ fixes - FixHPET, FixTMR, FixRTC, and FixIPIC.

You never ever want to touch /S/L/E, and you also don't need to install any kexts in /L/E or /S/L/E.

**Comment by Hunter9888x** [comment]
Ben9923 how do i get debug info

**Comment by fewtarius** [comment]
@Hunter9888x boot with debug=0x100 -v keepsyms=1 and then follow this guide:

https://github.com/alexandred/VoodooI2C/blob/master/Documentation/Troubleshooting.md

**Comment by Hunter9888x** [comment]
@ben9923 version 2.4 fixed my issue with
Apple i2c controller
