### ISSUE TITLE
Atmel 3000 compatibility 

### ISSUE THREAD

**Issue by fdalto** [alexandred/VoodooI2C#242]
Hello,
Is there any way of activating ATML3000 ?

I have a  Notebook Samsung NP350XAA-KFWBR With HID I2C VEN_ATML&DEV_3000 (Atmel)
Aida report: https://drive.google.com/open?id=1z5VVoD9iuDCv5EiLarMrWxgdkoi7223L
Origin: https://drive.google.com/open?id=1gfYc-ZJeaiG7Nh746f-DMKdnKUk7stlF

**Comment by ben9923** [comment]
You should have support, at least minimal.
Give VoodooI2C + VoodooI2CHID a try.
As it's not really an issue - closing it. Please re-open in case of an issue.
