### ISSUE TITLE
"Print Screen" Button

### ISSUE THREAD

**Issue by Ab2774** [alexandred/VoodooI2C#247]
Hi
There's a button in my keyboard called "Print Screen" or "PrtSc" as shown in the photo
when I click that button my trackpad get disabled completely until I press that button again 
Is there a way to disable that button or at least make it work with "Fn" keys just like the brightness keys 
Thanks.
My laptop: Lenovo Ideapad 320 14IKB with i5 7200U and ELAN Trackpad 
![IMG_4002](https://user-images.githubusercontent.com/60307632/75093572-f0662180-5593-11ea-91ad-6e35cea6e8e2.jpg)

**Comment by Goshin** [comment]
Are you using the VoodooPS2Controller for your keyboard? It is a "feature" of VoodooPS2Controller.

Try to remap the PS/2 scan code for the `Print Screen` key. Check out the tutorial here.
[How to Use Custom Keyboard Mapping](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/wiki/How-to-Use-Custom-Keyboard-Mapping)

**Comment by Ab2774** [comment]
Thank you so much, I've done some searching until I found this:
https://github.com/acidanthera/VoodooPS2/blob/master/Docs/ACPI/SSDT-PrtSc-F13.dsl
I used this SSDT and it's much easier
Thanks anyway
