### ISSUE TITLE
OS:10.14.6 err: unsupporter PCH

### ISSUE THREAD

**Issue by SkyWingZhang** [alexandred/VoodooI2C#248]
computer： lenovo air14 2019 i5-10210u

10.15.3: ok

but:
10.14.6:
err: unsupporter PCH

![6BD7EEC8082BD5FE37E871F8A6CB8FC1](https://user-images.githubusercontent.com/49492372/75096155-b6b70a00-55d7-11ea-9563-0415f5d0ef77.JPG)
![3D15E6F8F2EA754957CF3EDC0888E2D6](https://user-images.githubusercontent.com/49492372/75096156-b9196400-55d7-11ea-9932-f2ce87737df6.JPG)

Please address

**Comment by ben9923** [comment]
Not an issue with VoodooI2C.
Stick with latest macOS release for 10th Gen hardware, Mojave lacks compatibility for such hardware AFAIK.
