### ISSUE TITLE
Can i change trackpad tracking speed or acceleration? 

### ISSUE THREAD

**Issue by leezakka** [alexandred/VoodooI2C#249]
Hello. i'm using comet lake I2C-HID(pci8086,2e8).

First of all, thanks to use my I2C Device via your kext.

I have some questions about Trackpad setting.
I wanna adjust trackpad acceleration accurately and can change tracking speed in SysPre.Trackpad.
But I think it is so extreme. When I set it's speed fast, the acceleration is very fast. also set slow then It is so slow. 
I think it is little different from my real trackpad. 
Can I adjust this trackpad speed setting like real trackpad?

**Comment by kprinssu** [comment]
Sorry, but this is not supported. VoodooI2C spoofs/mimics the Apple hardware. If Apple's own hardware doesn't support it, then we cannot either.

Additionally, modify the acceleration is quite difficult.
