### ISSUE TITLE
High CPU Freq on Intel i5 7200U

### ISSUE THREAD

**Issue by vmtran123** [alexandred/VoodooI2C#262]
Firstly I'd like to thank you for your great work. It works like a charm even though trackpad not detected in System Preferences mojave (maybe it's my mistake). But after using the kext, my cpu keeps running on high frequency. Is there anyway to fix it.
--Before
![Screen Shot 2020-03-25 at 11 22 18](https://user-images.githubusercontent.com/45795835/77537411-9f1dba80-6ed0-11ea-8363-e72c84d6b11c.png)
--After:
![Screen Shot 2020-03-25 at 19 33 02](https://user-images.githubusercontent.com/45795835/77537459-bb215c00-6ed0-11ea-9072-18e4ee36d7f1.png)

**Comment by kprinssu** [comment]
This is a noted bug (see https://github.com/alexandred/VoodooI2C/issues/259), please read the other Github issues before creating a ticket.

Please also note those graphs are not useful at all.
