### ISSUE TITLE
Elan 1200

### ISSUE THREAD

**Issue by arvedviehweger** [alexandred/VoodooI2C#28]
Do you guys have any plans on adding support for the Elan1200? I think it's bot too different from the other ones. There is basic support for the Elan 1200 in the MacForOnce repo, but that doesn't include the features from the other Elan trackpads. 

Many people would like to have support for the Elan 1200, since it is very popular in Asus Laptops (100 and 200 series).

Thanks

**Comment by alexandred** [comment]
Merging MacForceOne's ELAN1200 support is planned but there need to be some changes to the main codebase to allow it. I don't have time to do it myself as it requires some research.
