### ISSUE TITLE
Gesture Recognition

### ISSUE THREAD

**Issue by nikhil19rathore99** [alexandred/VoodooI2C#286]
Launchpad gesture(3 fingures with thumb) is not working correctly in 2.4 version 
VodooI2C FTE1001 Asus Laptop

**Comment by kprinssu** [comment]
Please attach troubleshooting archive.

**Comment by nikhil19rathore99** [comment]
![Screenshot 2020-04-17 at 3 50 16 PM](https://user-images.githubusercontent.com/32436513/79559364-32f33880-80c3-11ea-9511-538c9ece86e5.png)
![Screenshot 2020-04-17 at 3 51 03 PM](https://user-images.githubusercontent.com/32436513/79559392-40a8be00-80c3-11ea-94b1-dca790fd35c6.png)

**Comment by williambj1** [comment]
@nikhil19rathore99 

Please delete your screenshots and follow the instructions here, https://voodooi2c.github.io/#Troubleshooting/Troubleshooting

YOU ARE WASTING THE DEVELOPERS' TIME!
https://github.com/williambj1/GenI2C#terms-of-use

**Comment by nikhil19rathore99** [comment]
![Screenshot 2020-04-22 at 6 40 05 PM](https://user-images.githubusercontent.com/32436513/79985801-c3b58400-84c8-11ea-9e3f-9554016e92b3.png)

**Comment by kprinssu** [comment]
@nikhil19rathore99 Please **read** https://voodooi2c.github.io/#Troubleshooting/Troubleshooting.

I am closing this issue until you post the troubleshooting archive.
