### ISSUE TITLE
DLL0704

### ISSUE THREAD

**Issue by nos1609** [alexandred/VoodooI2C#29]
Hi! I'm using a Dell XPS9350 with a synaptics I2C touchpad. However it's also routed through PS/2.
How can I help to bring up the normal use of it via I2C? Bothe the 2 I2C controllers are successfully detected with your kext, since they are on i7-6560U Skylake.
Here is some output from Linux, just in case it might help somehow...
```
[    4.728185] input: DLL0704:01 06CB:76AE Touchpad as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-8/i2c-DLL0704:01/0018:06CB:76AE.0001/input/input17
[    4.728264] hid-multitouch 0018:06CB:76AE.0001: input,hidraw0: I2C HID v1.00 Mouse [DLL0704:01 06CB:76AE] on i2c-DLL0704:01
```
@alexandred also you may be interessed by [this](https://github.com/roadrunner2/macbook12-spi-driver) to bring gesture support, hope this might help even if it's a linux-mac reverse-engeneered path.

**Comment by alexandred** [comment]
I have a 9550 with the same trackpad. Best to use PS/2 drivers for now (VoodooPS2 or ElanPS2Trackpad) as the Synaptics interface in VoodooI2C doesn't work on this device yet.
