### ISSUE TITLE
Unable to unload VoodooInput.kext

### ISSUE THREAD

**Issue by Goshin** [alexandred/VoodooI2C#291]
The retained instance of VoodooInput leaks after unloading VoodooI2C, so it is not able to be unloaded with `kextunload`.

```
(kernel) Can't unload kext me.kishorprins.VoodooInput; classes have instances:
(kernel)     Kext me.kishorprins.VoodooInput class VoodooInputSimulatorDevice has 1 instance.
Failed to unload me.kishorprins.VoodooInput - (libkern/kext) kext is in use or retained (cannot unload).
```

The VoodooInput instance is retained in `VoodooI2CNativeEngine::handleOpen` and should be released in `handleClose` when unloading.

https://github.com/alexandred/VoodooI2C/blob/3a92946e0867320fd993719c9be301ba18bbd993/Multitouch%20Support/Native/VoodooI2CNativeEngine.cpp#L134-L148

However, in `VoodooInput::stop()`: 

https://github.com/acidanthera/VoodooInput/blob/50943a9820e5a40c4987e84ddc4ce989bbf7dc52/VoodooInput/VoodooInput.cpp#L105-L107

```cpp
void VoodooInput::stop(IOService *provider) {
    
    ...
    
    if (parentProvider->isOpen(this)) {
        parentProvider->close(this);
    }
    
    super::stop(provider);
}
```

`parentProvider->close(this);` is not getting invoked because `VoodooI2CNativeEngine` doesn't override the `handleIsOpen(...)` method. The `IOService::handleIsOpen(...)` checks its internal instance and returns false here:

```cpp
bool IOService::handleIsOpen( 	const IOService * forClient ) const
{
    if( forClient)
	return( __owner == forClient );
    else
	return( __owner != forClient );
}
```

So we need to implement the `VoodooI2CNativeEngine::handleIsOpen(...)` method:
https://github.com/Goshin/VoodooI2C/commit/d832938f3a38d0181cffc9fa4f7538b1f397954a
```cpp
bool VoodooI2CNativeEngine::handleIsOpen(const IOService *forClient) const {
    return voodooInputInstance != NULL && forClient == voodooInputInstance;
}
```

and in VoodooInput, the block `if (parentProvider->isOpen(this)) {...}` needs to be moved into `VoodooInput::willTerminate()` before `stop()` or it seems cause deadlock when unloading. https://github.com/Goshin/VoodooInput/commit/7fafbda49ed020ac8e74f22975d143b9cc03ea18

**Comment by kprinssu** [comment]
@Goshin can you please create a PR with the above fixes?
