### ISSUE TITLE
Kernel Panic with non-HID I2C devices

### ISSUE THREAD

**Issue by coolstar** [alexandred/VoodooI2C#3]
Non-HID I2C devices exist and do not follow the HID standard, or they can appear to respond to HID but be non-functional as HID (e.g. Elan I2C trackpad on some chromebooks).

The best way to check for this is with ACPI. Non-HID devices do not have a compatible ID of PNP0C50.

Relevant source: https://github.com/alexandred/VoodooI2C/blob/master/VoodooI2C/VoodooI2C.cpp#L447

**Comment by coolstar** [comment]
Just talked with @alexandred on gitter. The _DSM method works as well, but VoodooI2C causes a kernel panic with non-HID devices.

**Comment by alexandred** [comment]
I feel like this has been fixed now, feel free to reopen if not.
