### ISSUE TITLE
V2.4.1 and above has buggy clicking

### ISSUE THREAD

**Issue by aspring14** [alexandred/VoodooI2C#309]
When I use the kext versions 2.4.1 or above, when clicking the trackpad it will act like a long press even if I click it really fast, making it not usable unless tap to click this on.
I'm on a Lenovo Ideapad S340 81N8003TUS. V2.4 there is sometimes random stopping and it caused a kernel panic in sleep mode once.

**Comment by Goshin** [comment]
Try to disable `force click and haptic feedback` in trackpad pref.

**Comment by kprinssu** [comment]
@aspring14 Please read https://voodooi2c.github.io/#Troubleshooting/Troubleshooting. Please follow those steps and then post a troubleshooting archive.

**Comment by aspring14** [comment]
Disabling Force Click and haptic feedback fixed it, updated to latest 2.4.2, I'll update if I get more kernel panics caused by VoodooI2C.
