### ISSUE TITLE
trackpad Not Working after sleep

### ISSUE THREAD

**Issue by sooxiaotong** [alexandred/VoodooI2C#31]

**Comment by alexandred** [comment]
While I am keen to fix this issue, I will have to close this as you have provided no details.

**Comment by fubizitch** [comment]
I am also having this issue, and I know others have.  After the computer goes to sleep for a length of time, the track pad will no longer function after the computer wakes back up.  I have to reboot to get the track pad to work again.

Asus UX305CA-OHM7-WH

**Comment by fubizitch** [comment]
I have El Capitan 10.11.6 with the latest VoodooI2C driver installed.  I used the guide from https://www.tonymacx86.com/threads/guide-asus-ux305ca-uhd.197229/ to install.

Any other information you need from me?

**Comment by alexandred** [comment]
This issue has been fixed in the rewrite. No ETA for it yet. Also note that this issue is closed.
