### ISSUE TITLE
Dell Venue 11 Pro 7140

### ISSUE THREAD

**Issue by Paddy159** [alexandred/VoodooI2C#33]
Hello Alexandre,
I own an DV11P (7140) with Core M processor. I read that you got the touchscreen working for your DV11P. Is multitouch working? Can you post a short guide for it?

Thanks a lot for your great work!

Paddy

**Comment by alexandred** [comment]
Visit the gitter page on http://gitter.im/alexandre_d/VoodooI2C for personal support.
