### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by aweorit** [alexandred/VoodooI2C#55]
Hello

I clone the repo and built all the kexts in Xcode 9.2, but they won't load because of an invalid signature:

```
Invalid signature -67050 for kext <OSKext 0x7fbee6d088b0 [0x7fff9608e5b0]> { URL = "file:///Library/Extensions/VoodooI2C.kext/", ID = "com.alexandred.VoodooI2C" }
```

How can I make it load? I have already disabled SIP. Should I use kext dev mode?

Can I sign it myself?

**Comment by aweorit** [comment]
Is there any way to enable right click with Elan touchpad?

**Comment by alexandred** [comment]
No there isn't.

**Comment by aweorit** [comment]
OK, what about the other questions?

**Comment by alexandred** [comment]
The invalid signature warning is not an error. If you didn't know that then you probably shouldn't be fiddling with development kexts and you should just wait for the release.
