### ISSUE TITLE
kp in sequoia

### ISSUE THREAD

**Issue by robi62** [alexandred/VoodooI2C#567]
hi I'm running sequoia on hp revolve g2 but after sleep cannot input my password nothing happening so I need to restart my
laptop then I get kp message on boot
 Kernel Extensions in backtrace:
         com.apple.iokit.IOHIDFamily(2.0)[616540D4-1BFC-322D-872D-5C1D9E5A9DC4]@0xffffff801c0f1000->0xffffff801c153fff
            dependency: com.apple.iokit.IOReportFamily(47)[DCBEB7F4-9899-3FDE-8285-620F8C87B32A]@0xffffff801c467000->0xffffff801c469ffnnot f
 If I don't use ic2 kext I cannot pinch screen for launchpad but after sleep no kp panic.
Any ideas?????
it is anAlps GlidePoint Trackpad
These are the loaded kext
Last login: Sun Dec  8 11:44:24 on ttys000
user@users-iMac ~ % kextstat | grep -E "Voodoo|voodoo" 
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   70    1 0xffffff8004d7a000 0x13000    0x13000    com.alexandred.VoodooI2CServices (1) B9FE9E08-E3BF-311D-8200-A52D7A41591A <6 3>
   82    2 0xffffff8004e5c000 0x1a000    0x1a000    as.acidanthera.voodoo.driver.PS2Controller (2.3.7) E71ECB24-8C3C-3ECB-8073-74F08FF56206 <17 9 7 6 3 1>
   85    0 0xffffff8004e76000 0xd000     0xd000     as.acidanthera.voodoo.driver.PS2Keyboard (2.3.7) 542CC450-2219-384C-B56A-9A03A9B02849 <82 61 9 7 6 3 1>
   86    0 0xffffff8004e83000 0x26000    0x26000    as.acidanthera.voodoo.driver.PS2Trackpad (2.3.7) B16534A1-00A7-3304-A671-720564032551 <82 61 7 6 3>   95   
  124    0 0xffffff8004e06000 0x1b000    0x1b000    me.kishorprins.VoodooInput (1.1.6) CAA8FE2A-93F0-3837-B1C7-8FB6EE79F304 <61 7 6 3>
  125    1 0xffffff8004d8d000 0x4e000    0x4e000    org.coolstar.VoodooGPIO (1.1) 5D44616D-F091-3D54-9F18-C1026ACD14EE <17 7 6 3>
  126    1 0xffffff8004ddb000 0x2b000    0x2b000    com.alexandred.VoodooI2C (2.9.1) 69CB149B-534C-3C16-81B2-378A0F8AE80B <125 70 61 18 17 7 6 3 1>
  127    0 0xffffff8004e21000 0x3b000    0x3b000    com.alexandred.VoodooI2CHID (1) 84ED0F48-9496-3ABA-8058-728AD4BC492A <126 61 17 7 6 3>
user@users-iMac ~ %

**Comment by kprinssu** [comment]
Next time, please read the GitHub issue template.
