### ISSUE TITLE
Always touch the touchpad by mistake when typing

### ISSUE THREAD

**Issue by zysidea** [alexandred/VoodooI2C#65]
Device: XiaoMi Pro [i7 8550U]

Hello,thanks for your contribution so that many many ppl can use touchpad, its alomost perfect. But there is a problem that always touch the touchpad by mistake when typing and that touch will make the wrong click event.

**Comment by bozma88** [comment]
up

**Comment by yaozaiyu** [comment]
+1

**Comment by 603857045** [comment]
I agree. This is an annoying problem.

**Comment by influenist** [comment]
This is also the case on Xiaomi NoteBook air 12.5. 
(Synaptic)
