### ISSUE TITLE
CPU running always max 3500ghz after install VoodooI2C

### ISSUE THREAD

**Issue by anonymous-writer** [alexandred/VoodooI2C#66]
Hello,
First of all thanks to your work.
My problem and I now also for others:
Trackpad ELAN 1200 is fully working but CPU running max 3500ghz.
Unfortunately, I have not found aany solution. Attached the problem report.

[bug_report_ASUS_Zenbook_UX330UA.zip](https://github.com/alexandred/VoodooI2C/files/1991308/bug_report_ASUS_Zenbook_UX330UA.zip)

**Comment by 603857045** [comment]
My problem is the same as yours. I replaced the VoodooI2C.kext with the 1.04 version ,  and the trackpad  worked  and the CPU run normally .   But the trackpad is not perfect.

**Comment by alexandred** [comment]
This issue has been fixed by reimplementing polling in VoodooI2CHID and will be part of v2.0.2 which I shall release soon. Users with this issue should reread the installation instructions when v2.0.2 is out and pay particular attention to the "Polling vs Interrupts" section.

**Comment by jardenliu** [comment]
That is awesome ~~   v2.0.2 is comming soon?

**Comment by alexandred** [comment]
Yes.

**Comment by anonymous-writer** [comment]
Thank you very much for your work. The Kext works like a charm.
![screenshot_2018-06-06 13 54 59_vhg9vs](https://user-images.githubusercontent.com/35840715/41038485-9edd263c-6996-11e8-82b4-191dc750cd71.jpg)

**Comment by alexandred** [comment]
I should point out that @anonymous-writer is using a test kext and v2.0.2 is not out yet.

**Comment by xuhadixu** [comment]
> I should point out that @anonymous-writer is using a test kext and v2.0.2 is not out yet.
because of this driver breaks laptops - be careful!
