### ISSUE TITLE
synaptics issue

### ISSUE THREAD

**Issue by penghubingzhou** [alexandred/VoodooI2C#68]
联想小新潮7000使用的也是i2c触摸板，但是是synaptics的，没法驱动，求尽快更新。
Hello @alexandred ,
My computer is Lenovo Xiaoxin Chao 7000,  which use an i2c touch pad. But it's Synaptics i2c touchpad and can't be drived by this  kexts. Could you please update the git repo soon to fix  this  problem? Thanks very much!

**Comment by influenist** [comment]
Did you apply the DSDT xosi (windows 10) patch ?

**Comment by penghubingzhou** [comment]
now it has
