### ISSUE TITLE
Scrolling up, can't stop with two finger tap.

### ISSUE THREAD

**Issue by abn5x** [alexandred/VoodooI2C#69]
When scrolling down (fingers going up) you can stop the momentum/inertia with two finger tap
but when you scroll up (fingers going down), you cannot stop it. The only way to stop the inertia is by doing a counter scrolling gesture in the oposite direction.

edit1 also the same thing happens when scrolling hoizontaly. everything is okey when scrolling to right(finger sliding from right to left), but scrolling to left doesnt stop with two finger tap.

**Comment by Andrw0830** [comment]
I can confirm this issue even with the latest VoodooI2C built from source and also with previous VoodooI2C versions since I have been using VoodooI2C over a month ago.
