### ISSUE TITLE
I2C devices' probe returns 0 on success.

### ISSUE THREAD

**Issue by coolstar** [alexandred/VoodooI2C#7]
I2C devices' probe functions are returning 0 (false) on success.

Affected Lines:
https://github.com/alexandred/VoodooI2C/blob/master/VoodooI2C/VoodooI2CHIDDevice.cpp#L59
https://github.com/alexandred/VoodooI2C/blob/master/VoodooI2C/VoodooCyapaGen3Device.cpp#L646

This appears to be the cause of freezes when loading/unloading the kext several times.

**Comment by alexandred** [comment]
Will look into it when I have time. Although I believe I was following Linux kernel standards where returning 0 means no errors and returning < 0 means an error has occurred. In future I will standardise the code base to follow Darwin kernel standards.
