### ISSUE TITLE
HID equipment fails after a period of use

### ISSUE THREAD

**Issue by LyricsGod** [alexandred/VoodooI2C#72]
lenovo ideapad 720s
The driving work is perfect, the computer can recognize the touch pad and multi-finger operation, but fails after a period of time

**Comment by alexandred** [comment]
I can't do anything if you do not provide me with a troubleshooting archive.

**Comment by xShiftx** [comment]
Same issue on ASUS K541UV with ELAN 1200: after activity touchpad usage device fails to works for some time(3-5 minutes), after it works again.

And, my ELAN 1200 recognized in Windows 10 as HID device but with ELAN kext solution won't work :) It works only with old style DSDT patches and HID kext.
