### ISSUE TITLE
Lenovo Yoga 910-13IKB - No Input

### ISSUE THREAD

**Issue by cepxuo** [alexandred/VoodooI2C#73]
**machine model:** Lenovo Yoga 910-13IKB
**CPU model:** 2,9 GHz Intel Core i7 Kaby Lake
**OS version:** 10.13.5
**The version of VoodooI2C:** 2.0.2. The following kexts from 2.0.2 version archive are installed into /EFI/CLOVER/kexts/Other:
  VoodooI2C.kext
  VoodooI2CHID.kext
**Patches applied:** 
[Windows] Windows 10 Patch
[GPIO] GPIO Controller Enable [SKL+] _(tried without this patch with same result)_

I see both trackpad and touch screen (as TPD0 and TPL1) in IORegistry. The APIC pins are 0x1f and 0x33. Both devices have property "compatible" set to <"PNP0C50">. So technically everything should work, but trackpad is not recognized in Trackpad section of System Control and there is no cursor reaction on trackpad gestures and button clicks. Nither happens with touch screen.

Attached are my patched DSDT, original DSDT and IORegistry output.
[Cepxuo.zip](https://github.com/alexandred/VoodooI2C/files/2103900/Cepxuo.zip)

**Comment by alexandred** [comment]
Well you have neglected to provide me with the full troubleshooting archives (there is no log) so I can't help you. In any case, this is not an appropriate place for this kind of question, you should seek support on the gitter chat or the tonymac forum, not here.
