### ISSUE TITLE
It can work in Xiaomi Notebook 12.5 CPU 6Y30

### ISSUE THREAD

**Issue by ykla** [alexandred/VoodooI2C#74]
Thanks a lot. It works on my notebook: xiaomi air 12.5 6Y30 skylake, but it very slow. 

10.13.5

**Comment by alexandred** [comment]
GitHub issues is definitely _not_ the place to post "it works". If you have a problem with "slowness" (whatever that means), you should seek help in the Gitter chat room (with troubleshooting archives provided).
