### ISSUE TITLE
Not work on 10.13.6

### ISSUE THREAD

**Issue by dedicahyadi** [alexandred/VoodooI2C#80]
Just updated from 10.13.5 to 10.13.6, after finish my touchpad elan1200 not work any more. Please help

**Comment by pqml** [comment]
Did you rebuild your kextcache ?

**Comment by dedicahyadi** [comment]
yes i did man,

**Comment by dedicahyadi** [comment]
any patch for 10.13.6????

**Comment by dedicahyadi** [comment]
cause working very well on 10.13.5

**Comment by alexandred** [comment]
This is not an appropriate issue for Github. You should have posted this in the Gitter chat or on the support forums. You should seek support in one of those venues.

**Comment by dedicahyadi** [comment]
sorry boss, i don’t know after restart several time, it’s woks like before. thanks
