### ISSUE TITLE
10.13.6 Wont work

### ISSUE THREAD

**Issue by xShiftx** [alexandred/VoodooI2C#81]
Diar Alexander.

Kexts won't work after 10.13.6 update.

Have you a plan to fix it for 10.14 also?

**Comment by ksymmonds** [comment]
Ditto. Solved by removing /S/L/E/AppleIntelLpssI2CController.kext and /S/L/E/AppleIntelLpssI2C.kext which were installed as part of the update process. Hope this helps?

**Comment by alexandred** [comment]
This would be a non-issue had you installed to Clover as the g

**Comment by xShiftx** [comment]
After sudo kextcache -i / it works again.
