### ISSUE TITLE
Mouse drift problem

### ISSUE THREAD

**Issue by zzyandzzy** [alexandred/VoodooI2C#86]
Hello, my problem is the same as [issues/44](https://github.com/alexandred/VoodooI2C/issues/44) After I used another driver [MacForceOne/VoodooI2C](https://github.com/MacForceOne/VoodooI2C) the mouse no longer drifts. The gestures are perfect (five fingers will cause to restart), how can I fix it? Thank you.

**Comment by zzyandzzy** [comment]
By the way, **MacForceOne/VoodooI2C** can cause hibernation instability and **kernel panic**

**Comment by alexandred** [comment]
Without troubleshooting archives I can only guess. If you are using the latest release then it is because you are running in polling mode and your device does not support it. You should run it in interrupt mode.

Macforceone's branch is old and should nto be used.
