### ISSUE TITLE
Trackpad for ASUS ZenBook UX300UAR Broken in v2.0.0

### ISSUE THREAD

**Issue by AwlsomeAlex** [alexandred/VoodooI2C#87]
I am using a ASUS ZenBook UX330UAR [8th Generation i5] (I don't know what trackpad is used) but when I use version 1.0.4 of the kext, it works **BUT** it is close to unusable since if you drag it will go on infinitely, and clicking is very glitchy. However starting with 2.0.0 it just doesn't work at all. Hoping to find a fix for this, or is there a possible DSDT patch for this? Thanks!

**Comment by alexandred** [comment]
Such questions should be asked in the Gitter chat, not on Github issues.

**Comment by AwlsomeAlex** [comment]
But it’s an issue. With your kext. Who else am I suppose to ask but the developer?

**Comment by ben9923** [comment]
You aren't describing an issue with the kext.
If you complete patching and correct setup for it, and you still have an issue (For example - kext prevents sleep on your machine, kext is causing a panic on shutdown...), then you should open an appropriate GitHub issue.
Please, ask for help in the Gitter chat room, as advised. You should also probably read the installation guide.

**Comment by xuhadixu** [comment]
> Such questions should be asked in the Gitter chat, not on Github issues.
because of this driver breaks laptops - be careful!
