### ISSUE TITLE
hidd CPU Usage

### ISSUE THREAD

**Issue by tboock** [alexandred/VoodooI2C#90]
First off: Thank you very much for your work. With latest releases the touchpad of my Dell XPS 13 works just perfect.

However I'm experiencing hidd to cause relatively high CPU usage with VoodooI2C 2.1 and 2.1.1 when the mouse cursor is being moved. With VoodooI2C 2.03 hidd CPU usage was around 5% for me. With latest releases it went up to 20%. Due to the CPU clock rate being raised, battery drain is caused.

**Comment by alexandred** [comment]
I am currently still investigating this. It turns out that kernel_task had a heavy CPU usage on v2.0.3 as well (upwards of 17%) so I am attempting to fix that first. I am not quite sure what the hidd cpu usage but we will get to it eventually.

**Comment by tboock** [comment]
I'm moving to another city and I'm pretty stuck in work. Will provide a troubleshooting archive when I finished some things. Thanks for having a look at this issue!

**Comment by xuhadixu** [comment]
because of this driver breaks laptops - be careful!

**Comment by xuhadixu** [comment]
> I am currently still investigating this. It turns out that kernel_task had a heavy CPU usage on v2.0.3 as well (upwards of 17%) so I am attempting to fix that first. I am not quite sure what the hidd cpu usage but we will get to it eventually.
/ Linux equivalent of FTE_i2c_write_cmd function
 IOReturn VoodooI2CFTETouchpadDriver::write_FTE_cmd(UInt16 reg, UInt16 cmd) {
     UInt16 buffer[] {
         reg,
         cmd
     };
     IOReturn retVal = kIOReturnSuccess;
     retVal = api->writeI2C(reinterpret_cast<UInt8*>(&buffer), sizeof(buffer));
     return retVal;
 }
 
 IOReturn VoodooI2CFTETouchpadDriver::message(UInt32 type, IOService* provider, void* argument)
 {
     switch (type)
     {
         case kKeyboardGetTouchStatus:
         {
 #if DEBUG
             IOLog("%s::getEnabledStatus = %s\n", getName(), ignoreall ? "false" : "true");
 #endif

**Comment by vcreatyv** [comment]
> Can you please provide a troubleshooting archive.
However I'm experiencing hidd to cause relatively high CPU usage with VoodooI2C 2.1 and 2.1.1 when the mouse cursor is being moved. With VoodooI2C 2.03 hidd CPU usage was around 5% for me. With latest releases it went up to 20%. Due to the CPU clock rate being raised, battery drain is caused.

**Comment by ben9923** [comment]
This issue is fixed in v2.1.2+
You may get latest release (currently 2.1.4) from the [releases page](https://github.com/alexandred/VoodooI2C/releases).
