### ISSUE TITLE
Xiaomi game Ben eight generation touchpad can not be driven in mac os 10.14

### ISSUE THREAD

**Issue by chuntaojun** [alexandred/VoodooI2C#91]
Alexandred, is it still not adapted to mac os 10.14? My Xiaomi game version of this eight-generation enhanced version installed mac os 10.14 version, but due to I2C touchpad problems, read the relevant issue and your project page still can not drive my touchpad, I would like to ask you to help me

**Comment by alexandred** [comment]
It is clear from the release notes of v2.1.1 that Mojave is not supported.

**Comment by chuntaojun** [comment]
> It is clear from the release notes of v2.1.1 that Mojave is not supported.

ok
