### ISSUE TITLE
Jittery Mouse Movement on 2.1.1

### ISSUE THREAD

**Issue by mashnoon33** [alexandred/VoodooI2C#94]
I am using version 2.1.1 on 10.13.6 on a XPS 9360. The mouse movement is pretty jittery using the latest release.

Video Example : https://youtu.be/Lbkt6wBHrIs

**Comment by jardenliu** [comment]
maybe you can try to disable the  ACPIBatteryManager.kext

**Comment by jardenliu** [comment]
Use ACPIBatteryManager  V1.81.4 instead

**Comment by alexandred** [comment]
Closing as this does not appear to be related to VoodooI2C.

**Comment by trlsmax** [comment]
cursor still jump when moving after update ACPIBatteryManager to latest version. If I remove ACPIBatteryManager, cursor moving ok
