### ISSUE TITLE
Eight generations of device touch drive problems

### ISSUE THREAD

**Issue by chuntaojun** [alexandred/VoodooI2C#95]
Hello, when I refer to your tutorial, I found that the touch driver code has been around for a while. I have never seen anyone else. The entire tutorial looks like only the code here is different. Have you ever been exposed to an eight-generation device like this?

![77a72e33d15348e8309108b1485b20fc](https://user-images.githubusercontent.com/23445172/45944081-6b33b180-c01b-11e8-8669-ab04f88c7648.jpg)

**Comment by alexandred** [comment]
`I2CM (I2CX, BADR, SPED)` is effectively `SBFB`. So just replace `SBFI` with `SBFG` while GPIO pinning.

**Comment by chuntaojun** [comment]
Ok, I'll try it.  thank you

**Comment by chuntaojun** [comment]
> `I2CM (I2CX, BADR, SPED)` is effectively `SBFB`. So just replace `SBFI` with `SBFG` while GPIO pinning.

What frustrates me is that it still doesn't work.

**Comment by alexandred** [comment]
You should seek further help on the Gitter chat instead of here. Please visit the chat and provide your full troubleshooting archives.

**Comment by chuntaojun** [comment]
> You should seek further help on the Gitter chat instead of here. Please visit the chat and provide your full troubleshooting archives.

I temporarily solved the problem with this trackpad.

**Comment by xuhadixu** [comment]
хорошо что комп не сгорел,фейковый драйвер

**Comment by xuhadixu** [comment]
> You should seek further help on the Gitter chat instead of here. Please visit the chat and provide your full troubleshooting archives.
/ Linux equivalent of FTE_i2c_write_cmd function
 IOReturn VoodooI2CFTETouchpadDriver::write_FTE_cmd(UInt16 reg, UInt16 cmd) {
     UInt16 buffer[] {
         reg,
         cmd
     };
     IOReturn retVal = kIOReturnSuccess;
     retVal = api->writeI2C(reinterpret_cast<UInt8*>(&buffer), sizeof(buffer));
     return retVal;
 }
 
 IOReturn VoodooI2CFTETouchpadDriver::message(UInt32 type, IOService* provider, void* argument)
 {
     switch (type)
     {
         case kKeyboardGetTouchStatus:
         {
 #if DEBUG
             IOLog("%s::getEnabledStatus = %s\n", getName(), ignoreall ? "false" : "true");
 #endif
