### ISSUE TITLE
Can't boot to to macOS 10.13.6 on ver v2.1.2

### ISSUE THREAD

**Issue by cookievu** [alexandred/VoodooI2C#99]
My trackpad work fine on v2.1.1 and old. But when upgrade to v2.1.2, my laptop can't boot into login screen.
My trackpad is Elan 1200 and use VoodooI2C & VoodooI2CHID kext.
Sorry my bad English.

**Comment by xuhadixu** [comment]
because of this driver breaks laptops - be careful!

**Comment by cookievu** [comment]
@stevezhengshiqi  i put it /CLOVER/kexts/10.13

**Comment by cookievu** [comment]
@xuhadixu Is there a way to fix it?

**Comment by hieplpvip** [comment]
You have to boot to recovery mode to remove it

**Comment by cookievu** [comment]
@hieplpvip thanks. I returned to the older version and waited until there was a patch.
